/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproyectofinal;

/**
 *
 * @author martin
 */
public class EditarFrame extends javax.swing.JFrame {

    
    private PRINCIPAL principal;
    private int fila;
   
    
    
    public EditarFrame(PRINCIPAL principal, int fila, String nombre, String apellido, String correo, String telefono, String direccion, String estadoCivil ) {  // RETORNARMOS PARA QUE  ME DE VALORES TABLA
        
     initComponents();
        
     
     
        camponombreeditar.setText(nombre);
        campoapellidoeditar.setText(apellido);
        campocorreoeditar.setText(correo);
        campotelefonoeditar.setText(telefono);
        campodireccioneditar.setText(direccion);
    
   
        if ("Soltero".equals(estadoCivil)) {
            jRadioButton1.setSelected(true);
        } else if ("Casado".equals(estadoCivil)) {
            jRadioButton2.setSelected(true);
        } else if ("Divorsiado".equals(estadoCivil)) {
            jRadioButton3.setSelected(true);
        } else if ("Union libre".equals(estadoCivil)) {
            jRadioButton4.setSelected(true);
        }

        this.principal = principal;
        this.fila = fila;
        
        
         
        
    }

    
    
    
    
    private EditarFrame() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        camponombreeditar = new javax.swing.JTextField();
        campoapellidoeditar = new javax.swing.JTextField();
        campocorreoeditar = new javax.swing.JTextField();
        campotelefonoeditar = new javax.swing.JTextField();
        campodireccioneditar = new javax.swing.JTextField();
        guardarbotoneditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuitemeditar_editar = new javax.swing.JMenuItem();
        menuitemsalir_editar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Divorsiado");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Union lbre");

        guardarbotoneditar.setText("Editar");
        guardarbotoneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarbotoneditarActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese su nombre");

        jLabel2.setText("Ingrese su apellido");

        jLabel3.setText("Ingrese su  correo");

        jLabel4.setText("Ingrese su numero");

        jLabel5.setText("Ingrese su direccion");

        jLabel6.setText("Ingrese su estado civil");

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Soltero");

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Casado");

        jMenu1.setText("Ayuda");

        menuitemeditar_editar.setText("Editar");
        menuitemeditar_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemeditar_editarActionPerformed(evt);
            }
        });
        jMenu1.add(menuitemeditar_editar);

        menuitemsalir_editar.setText("Salir");
        menuitemsalir_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemsalir_editarActionPerformed(evt);
            }
        });
        jMenu1.add(menuitemsalir_editar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(guardarbotoneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(camponombreeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoapellidoeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campocorreoeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campodireccioneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campotelefonoeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(camponombreeditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoapellidoeditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campocorreoeditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(campotelefonoeditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campodireccioneditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton4))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardarbotoneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
/////////////////////////////////////////////////////////////////////////////////////////////todo para que el boton haga la accion/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
     
    
    
    
    
    private void guardarbotoneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarbotoneditarActionPerformed
       
        String nombre = camponombreeditar.getText();
        String apellido = campoapellidoeditar.getText();
        String correo = campocorreoeditar.getText();
        String telefono = campotelefonoeditar.getText();
        String direccion = campodireccioneditar.getText();
    
        String estadoCivil = "";
            if (jRadioButton1.isSelected()) {
                estadoCivil = "Soltero";
            }    
          
            else if (jRadioButton2.isSelected()) {
                estadoCivil = "Casado";
            }    
                
             else if (jRadioButton3.isSelected()) {
                estadoCivil = "Divorsiado";
            }    
                
             else if (jRadioButton4.isSelected()) {
                estadoCivil = "Union libre";
            }

            
        principal.actualizarContacto(fila, nombre, apellido, correo, telefono, direccion, estadoCivil);
        this.dispose();
        
    }//GEN-LAST:event_guardarbotoneditarActionPerformed

    
    
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    
    
    
   
    
    
//////////////////////////////////////////////////////////////////////////////// MENU ITEM PARA QUE ME HAGA LO MISMO QUE EL BOTON//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    
    
    private void menuitemeditar_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemeditar_editarActionPerformed
       
        String nombre = camponombreeditar.getText();
            String apellido = campoapellidoeditar.getText();
            String correo = campocorreoeditar.getText();
            String telefono = campotelefonoeditar.getText();
            String direccion = campodireccioneditar.getText();

            String estadoCivil = "";
                if (jRadioButton1.isSelected()) {
                    estadoCivil = "Soltero";
                }    

                else if (jRadioButton2.isSelected()) {
                    estadoCivil = "Casado";
                }    

                 else if (jRadioButton3.isSelected()) {
                    estadoCivil = "Divorsiado";
                }    

                 else if (jRadioButton4.isSelected()) {
                    estadoCivil = "Union libre";
                }


            principal.actualizarContacto(fila, nombre, apellido, correo, telefono, direccion, estadoCivil);
            this.dispose();

                

        
        
        
        
        
    }//GEN-LAST:event_menuitemeditar_editarActionPerformed

    
    
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    
    
    
    
    
    
    private void menuitemsalir_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemsalir_editarActionPerformed
      
         dispose();
        
    }//GEN-LAST:event_menuitemsalir_editarActionPerformed

    
    
    
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
              PRINCIPAL principal = new PRINCIPAL(); // O el objeto que tengas
            int fila = 0; // O el valor que tengas
            String nombre = "Nombre";
            String apellido = "Apellido";
            String correo = "correo@example.com";
            String telefono = "123456789";
            String direccion = "Dirección";
            String estadoCivil = "Soltero";    
                
                
                
                
                
                
                
                
                new EditarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField campoapellidoeditar;
    private javax.swing.JTextField campocorreoeditar;
    private javax.swing.JTextField campodireccioneditar;
    private javax.swing.JTextField camponombreeditar;
    private javax.swing.JTextField campotelefonoeditar;
    private javax.swing.JButton guardarbotoneditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JMenuItem menuitemeditar_editar;
    private javax.swing.JMenuItem menuitemsalir_editar;
    // End of variables declaration//GEN-END:variables
}

