/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproyectofinal;

import java.awt.event.KeyEvent;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author martin
 */
public class FormularioFrame extends javax.swing.JFrame {
 private PRINCIPAL principal;
 private ButtonGroup grupoBotones;
 
 
 
    /**
     * Creates new form FormularioFrame
     */
    public FormularioFrame(PRINCIPAL principal) {
        
        initComponents();
        this.principal = principal;
        requestFocusInWindow(); 
    
     
        grupoBotones = new ButtonGroup();
        grupoBotones.add(jRadioButton1);
        grupoBotones.add(jRadioButton2);
        grupoBotones.add(jRadioButton3);
        grupoBotones.add(jRadioButton4);
        
        
        
        
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        guardarboton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        camponombre = new javax.swing.JTextField();
        campoapellido = new javax.swing.JTextField();
        campocorreo = new javax.swing.JTextField();
        campotelefono = new javax.swing.JTextField();
        campodireccion = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuitemsalir_gregar = new javax.swing.JMenuItem();
        menuitemguardar_guardar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        guardarboton.setText("Agregar");
        guardarboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarbotonActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese su nombre");

        jLabel2.setText("Ingrese su apellido");

        jLabel3.setText("Ingrese su  correo");

        jLabel4.setText("Ingrese su numero");

        jLabel5.setText("Ingrese su direccion");

        jLabel6.setText("Ingrese su estado civil");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Soltero");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Casado");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Divorsiado");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Union lbre");

        jMenu1.setText("Ayuda");

        menuitemsalir_gregar.setText("Salir");
        menuitemsalir_gregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemsalir_gregarActionPerformed(evt);
            }
        });
        jMenu1.add(menuitemsalir_gregar);

        menuitemguardar_guardar.setText("Guardar");
        menuitemguardar_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemguardar_guardarActionPerformed(evt);
            }
        });
        jMenu1.add(menuitemguardar_guardar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(guardarboton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(camponombre, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campocorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campodireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campotelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(camponombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campocorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(campotelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campodireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton4))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardarboton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    

    
    
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////// PARTE DE TODO EL CAMPO  CON VALIDACIONES  ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    
    
    private void guardarbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarbotonActionPerformed
    
        
        String nombre = camponombre.getText();
        String apellido = campoapellido.getText();
        String correo = campocorreo.getText();
        String telefono = campotelefono.getText();
        String direccion = campodireccion.getText();
        String estadoCivil = "";
            if (jRadioButton1.isSelected()) {
                estadoCivil = "Soltero";
            } else if (jRadioButton2.isSelected()) {
                estadoCivil = "Casado";
            } else if (jRadioButton3.isSelected()) {
                estadoCivil = "Divorciado";
            } else if (jRadioButton4.isSelected()) {
                estadoCivil = "Union Libre";
            }
    
        
        
        
        
        
        
        
        
            if (telefono.isEmpty()) {
                JOptionPane.showMessageDialog(this, "el número de teléfono no puede estar vacio.");
                return; 
            }




            
            if (!telefono.matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "el numero de telefono debe contener solo numeros.");
                return;
            }

            
            
            
            
   
            if (!validarCorreo(correo)) {
                JOptionPane.showMessageDialog(this, "el correo electronico no es valido este debe contener '@' y terminar con '.com'.");
                return; 
            }

    
            
            
            
            if (noiguales(nombre, telefono)) {
                JOptionPane.showMessageDialog(this, "ya existe un contacto con ese nombre o número.");
                return;
            }

            
            
            
            
  
        DefaultTableModel model = principal.getTablaContenidoModel();
        model.addRow(new Object[]{nombre, apellido, correo, telefono, direccion, estadoCivil});

   
        
        
        this.dispose();
    
   
        
    }//GEN-LAST:event_guardarbotonActionPerformed

    
    
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
     
    
    
    
    
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
     if (evt.getKeyCode() == KeyEvent.VK_G) { 
        guardarboton.doClick(); 
    } 
        
    }//GEN-LAST:event_formKeyPressed

    
       
    
    
    private void menuitemsalir_gregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemsalir_gregarActionPerformed
            
             dispose();
               
    }//GEN-LAST:event_menuitemsalir_gregarActionPerformed

    
    
    
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////// BOTON BAR PARA QUE TMAIEN GUARDE  ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
     
    
    
    
    private void menuitemguardar_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemguardar_guardarActionPerformed
        
        String nombre = camponombre.getText();
        String apellido = campoapellido.getText();
        String correo = campocorreo.getText();
        String telefono = campotelefono.getText();
        String direccion = campodireccion.getText();
        String estadoCivil = "";
            if (jRadioButton1.isSelected()) {
                estadoCivil = "Soltero";
            } else if (jRadioButton2.isSelected()) {
                estadoCivil = "Casado";
            } else if (jRadioButton3.isSelected()) {
                estadoCivil = "Divorciado";
            } else if (jRadioButton4.isSelected()) {
                estadoCivil = "Union Libre";
            }
    
        
        
        
        
        
        
        
        
            if (telefono.isEmpty()) {
                JOptionPane.showMessageDialog(this, "el número de teléfono no puede estar vacio.");
                return; 
            }




            
            if (!telefono.matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "el numero de telefono debe contener solo numeros.");
                return;
            }

            
            
            
            
   
            if (!validarCorreo(correo)) {
                JOptionPane.showMessageDialog(this, "el correo electronico no es valido este debe contener '@' y terminar con '.com'.");
                return; 
            }

    
            
            
            
            if (noiguales(nombre, telefono)) {
                JOptionPane.showMessageDialog(this, "ya existe un contacto con ese nombre o número.");
                return;
            }

            
            
            
            
  
        DefaultTableModel model = principal.getTablaContenidoModel();
        model.addRow(new Object[]{nombre, apellido, correo, telefono, direccion, estadoCivil});

   
        
        
        this.dispose();
    
   
        
    }//GEN-LAST:event_menuitemguardar_guardarActionPerformed

    
    
    private boolean noiguales(String nombre, String telefono) {
        
        DefaultTableModel model = principal.getTablaContenidoModel();

  
            for (int i = 0; i < model.getRowCount(); i++) {

                Object nombreExistente = model.getValueAt(i, 0); 
                Object telefonoExistente = model.getValueAt(i, 3); 


                if ((nombreExistente != null && nombreExistente.toString().equals(nombre)) || 
                    (telefonoExistente != null && telefonoExistente.toString().equals(telefono))) {
                    return true; 
                    }
                }
            return false; 
    }
    
    
    
    
    
    
    
    private boolean validarCorreo(String correo) {
        return correo.contains("@") && correo.endsWith(".com");
        }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
   
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
     
    
    
    
    
   
   
   
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoapellido;
    private javax.swing.JTextField campocorreo;
    private javax.swing.JTextField campodireccion;
    private javax.swing.JTextField camponombre;
    private javax.swing.JTextField campotelefono;
    private javax.swing.JButton guardarboton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JMenuItem menuitemguardar_guardar;
    private javax.swing.JMenuItem menuitemsalir_gregar;
    // End of variables declaration//GEN-END:variables
}
