/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproyectofinal;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author martin
 */
public class PRINCIPAL extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    
    
    private boolean actionExecuted = false;
    private DefaultTableModel model;
    private JTable tabla;
    
    
    public PRINCIPAL() {
        initComponents();
        
       
   this.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            formKeyPressed(evt);
        }
        
        public void keyReleased(java.awt.event.KeyEvent evt) {
            actionExecuted = false; // Restablece cuando se suelta la tecla
        }
    });

    this.setFocusable(true);
    this.requestFocusInWindow();
        
       
    String[] columnNames = {"Nombre", "Apellido", "Correo", "Teléfono", "Dirección", "Estado Civil"};
    tableModel = new DefaultTableModel(columnNames, 0);
        tablacontenido.setModel(tableModel);
    
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botonagregar = new javax.swing.JButton();
        botoneditar = new javax.swing.JButton();
        botoneliminar = new javax.swing.JButton();
        botonbuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablacontenido = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menubarnuevo = new javax.swing.JMenu();
        menuitemsalir = new javax.swing.JMenuItem();
        menuitemagregar = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        botonagregar.setText("Agregar");
        botonagregar.setFocusable(false);
        botonagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonagregarActionPerformed(evt);
            }
        });

        botoneditar.setText("Editar");
        botoneditar.setFocusable(false);
        botoneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneditarActionPerformed(evt);
            }
        });

        botoneliminar.setText("Eliminar");
        botoneliminar.setFocusable(false);
        botoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarActionPerformed(evt);
            }
        });

        botonbuscar.setText("Buscar");
        botonbuscar.setFocusable(false);
        botonbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonbuscarActionPerformed(evt);
            }
        });

        tablacontenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Correo  Electronico", "Numero", "Direccion", "Estado Civil"
            }
        ));
        tablacontenido.setFocusable(false);
        jScrollPane2.setViewportView(tablacontenido);

        menubarnuevo.setText("Archivo");

        menuitemsalir.setText("Salir");
        menuitemsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemsalirActionPerformed(evt);
            }
        });
        menubarnuevo.add(menuitemsalir);

        menuitemagregar.setText("Agregar");
        menuitemagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemagregarActionPerformed(evt);
            }
        });
        menubarnuevo.add(menuitemagregar);

        jMenuBar1.add(menubarnuevo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(botonagregar)
                .addGap(59, 59, 59)
                .addComponent(botoneditar)
                .addGap(62, 62, 62)
                .addComponent(botoneliminar)
                .addGap(78, 78, 78)
                .addComponent(botonbuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonagregar)
                    .addComponent(botoneditar)
                    .addComponent(botoneliminar)
                    .addComponent(botonbuscar))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////// PARA QUE ME ABRA EL FORMULARIO ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////  
    
    
    private void botonagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonagregarActionPerformed
        FormularioFrame formulario = new FormularioFrame(this);
        formulario.setVisible(true);
        
    }//GEN-LAST:event_botonagregarActionPerformed

    
 /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 
    
    ///////////////////////////////////////////////////////////////////////////////////////////////// BOTON PARA EDITAR////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    
    
    private void botoneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneditarActionPerformed
      
         
        
        int filaSeleccionada = tablacontenido.getSelectedRow();



            if (filaSeleccionada != -1) {
                    String nombre = (String) tablacontenido.getValueAt(filaSeleccionada, 0);
                    String apellido = (String) tablacontenido.getValueAt(filaSeleccionada, 1);
                    String correo = (String) tablacontenido.getValueAt(filaSeleccionada, 2);
                    String telefono = (String) tablacontenido.getValueAt(filaSeleccionada, 3);
                    String direccion = (String) tablacontenido.getValueAt(filaSeleccionada, 4);
                    String estadoCivil = (String) tablacontenido.getValueAt(filaSeleccionada, 5);




            EditarFrame editarFrame = new EditarFrame(this, filaSeleccionada, nombre, apellido, correo, telefono, direccion, estadoCivil);
            editarFrame.setVisible(true);

                                        } 


            else {

            JOptionPane.showMessageDialog(this, "Seleccione un contacto para editar.");
                    }

        
        
        
    }//GEN-LAST:event_botoneditarActionPerformed

    
   
    
    
    public void actualizarContacto(int fila, String nombre, String apellido, String correo, String telefono, String direccion, String estadoCivil) {

            DefaultTableModel model = (DefaultTableModel) tablacontenido.getModel();
            model.setValueAt(nombre, fila, 0);
            model.setValueAt(apellido, fila, 1);
            model.setValueAt(correo, fila, 2);
            model.setValueAt(telefono, fila, 3);
            model.setValueAt(direccion, fila, 4);
            model.setValueAt(estadoCivil, fila, 5);
                
    
        } 
    
    
    
    
    
    
    
 /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
       
    
    
    
    
    
    
    
    
////////////////////////////////////////////////////////////////////////////////////////////////////////////BOTON PARA ELIMINAR /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        
    
    
    private void botoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarActionPerformed
        
        
        int filaSeleccionada = tablacontenido.getSelectedRow(); 

            if (filaSeleccionada != -1) { 
                DefaultTableModel model = (DefaultTableModel) tablacontenido.getModel();
                model.removeRow(filaSeleccionada); 

                JOptionPane.showMessageDialog(this, "Contacto eliminado correctamente.");  

                } 



            else {

                JOptionPane.showMessageDialog(this, "seleccione un contacto para eliminar.");
                        } 



    }//GEN-LAST:event_botoneliminarActionPerformed

    
    
 /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
       
    
    
    
  
    
    
    
    
    
//////////////////////////////////////////////////////////////////////////////////////////////////// BOTON PARA BUSCAR/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        
    
    private void botonbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonbuscarActionPerformed
       
    BuscarFrame buscarFrame = new BuscarFrame(this);
    buscarFrame.setVisible(true);
        
        
    }//GEN-LAST:event_botonbuscarActionPerformed

    
    
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
       
    
    
    
    
 
///////////////////////////////////////////////////////////////////////////////////////////PARA LA VALIDACION DE TECLAS//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
       
        if (!actionExecuted) { 
            if (evt.getKeyCode() == KeyEvent.VK_N) {
                botonagregarActionPerformed(null);
                actionExecuted = true;
                    } 
            
            else if (evt.getKeyCode() == KeyEvent.VK_E) {
                botoneditarActionPerformed(null);
                actionExecuted = true;
                    } 
            
            else if (evt.getKeyCode() == KeyEvent.VK_D) {
                botoneliminarActionPerformed(null);
                actionExecuted = true;
                    }
            }

        
    }//GEN-LAST:event_formKeyPressed

    
    
 /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
       
    
    
    
    private void menuitemsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemsalirActionPerformed
       
          dispose();
        
        
    }//GEN-LAST:event_menuitemsalirActionPerformed

    
    
    
    
    private void menuitemagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemagregarActionPerformed
       FormularioFrame formulario = new FormularioFrame(this);
       formulario.setVisible(true);
    }//GEN-LAST:event_menuitemagregarActionPerformed
   
    
    
    
    
    
    
   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////// PARA AGREGAR VONTENIDO A LA TABLA ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////    
    
    
    
    public void agregarContacto(String nombre, String apellido, String correo, String telefono, String direccion, String estadoCivil) {
    
            DefaultTableModel model = (DefaultTableModel) tablacontenido.getModel();
            model.addRow(new Object[]{nombre, apellido, correo, telefono, direccion, estadoCivil});
        }
    
    
    
    
    
    public DefaultTableModel getTablaContenidoModel() {
         return (DefaultTableModel) tablacontenido.getModel();
        }
    
    
  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        

        
   
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonagregar;
    private javax.swing.JButton botonbuscar;
    private javax.swing.JButton botoneditar;
    private javax.swing.JButton botoneliminar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu menubarnuevo;
    private javax.swing.JMenuItem menuitemagregar;
    private javax.swing.JMenuItem menuitemsalir;
    private javax.swing.JTable tablacontenido;
    // End of variables declaration//GEN-END:variables
}
